model: Sim-v0 # StickInsect-v0
exclude_xy: True
env:
  seed: 42
  horizon: 3000
  
# irl: maxent
cuda: 4
mode: 'test' # [train, evaluate, test]
data_source: CarausiusC00AG
test_folder: 'test_folder/maxent/Carausius/ante_gait/'
# CarausiusC00, AretaonC00, MedauroideaC00, C00
# MedauroideaC00_untrimmed, C00_untrimmed
# CarausiusC00AG

# expert demonstration
CarausiusC00:
  No1: "01"
  No2: "02"
  No3: "03"
  vel_bin_params: [0, 145, 5]
  direction_bin_params: [-20, 10, 5]
  acc_bin_params: [-3000, 2750, 250]
AretaonC00:
  No1: "13"
  No2: "14"
  No3: "15"
  vel_bin_params: [0, 95, 5]
  direction_bin_params: [-20, 5, 5]
  acc_bin_params: [-2000, 1500, 250]
MedauroideaC00:
  No1: "25"
  No2: "26"
  No3: "27"
  vel_bin_params: [0, 120, 5]
  direction_bin_params: [-10, 15, 5]
  acc_bin_params: [-1250, 1750, 250]
C00:
  No1: "01"
  No2: "02"
  No3: "03"
  No13: "13"
  No14: "14"
  No15: "15"
  No25: "25"
  No26: "26"
  No27: "27"
  vel_bin_params: [0, 145, 5]
  direction_bin_params: [-20, 15, 5]
  acc_bin_params: [-3000, 2750, 250]
MedauroideaC00_untrimmed:
  No1: "25"
  No2: "26"
  No3: "27"
  vel_bin_params: [0, 125, 5]
  direction_bin_params: [-25, 35, 5]
  acc_bin_params: [-2750, 2000, 250]
C00_untrimmed:
  No1: "01"
  No2: "02"
  No3: "03"
  No13: "13"
  No14: "14"
  No15: "15"
  No25: "25"
  No26: "26"
  No27: "27"
  vel_bin_params: [0, 145, 5]
  direction_bin_params: [-25, 35, 5]
  acc_bin_params: [-3000, 2750, 250]
CarausiusC00AG:
  No1: "01"
  No2: "02"
  No3: "03"

grouped_gait_combinations:
  # representative noncanonical
  '111111': 5
  '111110': 5
  '111101': 5
  '111011': 5
  '110111': 5
  '101111': 5
  '011111': 5
  # tetrapod gait
  '110101': 4
  '110011': 4
  '101110': 4
  '101011': 4
  '011110': 4
  '011101': 4
  # tripod gait
  '101010': 3
  '010101': 3
  # tetrapod gait (noncanonical)
  '111010': 2
  '111001': 2
  '110110': 2
  '101101': 2
  '100111': 2
  '011011': 2
  '010111': 2
  '001111': 2
  # tripod gait (noncanonical)
  '110010': 1
  '101001': 1
  '011010': 1
  '011001': 1
  '010011': 1
  '001011': 1
  # rare noncanonical
  '101000': 0
  '100010': 0
  '001010': 0
  '000101': 0
  '000010': 0