# StickInsect-v0: PosVel
# StickInsect-v1: Motor
# StickInsect-v2: PosVel sensor
model: StickInsect-v0
learning_rate: 0.001
epochs: 1000

# SrickInsect-v0: PosVel w/o torso
# StickInsect-v1: PosVel w/ torso