# StickInsect-v0: PosVel
# StickInsect-v1: Motor
# StickInsect-v2: PosVel sensor
model: StickInsect-v1
learning_rate: 0.001
epochs: 1000

# SrickInsect-v0.npy: PosVel w/o torso
# StickInsect-v0.1.npy: PosVel w/ torso